name: semver

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/semver.yml@develop
