name: terraform 

on:
  push:
    branches:
      - develop

jobs:
  report:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Terraform apply
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env_production
          make apply
